kolesa/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/mizamidin/')),
]
from django.urls import include

urlpatterns += [
    path('mizamidin/', include('mizamidin.urls')),
]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mizamidin/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('cars/', views.CarListView.as_view(), name='cars'),
    path('car/<int:pk>', views.CarDetailView.as_view(), name='car-detail'),
    path('sellers/', views.SellerListView.as_view(), name='sellers'),
    path('seller/<int:pk>', views.SellerDetailView.as_view(), name='seller-detail'),
]
urlpatterns += [  
    path('seller/create/', views.SellerCreate.as_view(), name='seller_create'),
    path('seller/<int:pk>/update/', views.SellerUpdate.as_view(), name='seller_update'),
    path('seller/<int:pk>/delete/', views.SellerDelete.as_view(), name='seller_delete'),
]

mizamidin/models.py
from django.db import models
import uuid
import datetime
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from datetime import date

# Create your models here.
class Type(models.Model):

    name = models.CharField(max_length=200, help_text="Enter a car type ")
    
    def __str__(self):

        return self.name

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Car(models.Model):

    car_title = models.CharField(max_length=200)
    seller = models.ForeignKey('Seller', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the car")
    isbn = models.CharField('ISBN',max_length=13, help_text='Gost Nomer')
    type = models.ManyToManyField(Type, help_text="Select a type for this car")
    price_car = models.CharField(max_length=20)
    standart = models.CharField(max_length=20)
    date_vp = models.DateField(null=True, blank=True)
    car_ava = models.ImageField(upload_to='car_avas/', null=True, blank=True)
    


    def display_type(self):

        return ', '.join([ type.name for type in self.type.all()[:3] ])
    display_type.short_description = 'Type'
    
    def __str__(self):

        return self.car_title
    
    
    def get_absolute_url(self):

        return reverse('car-detail', args=[str(self.id)])
    def display_type(self):

        return ', '.join([ type.name for type in self.type.all()[:3] ])
    display_type.short_description = 'Type'
import uuid # Required for unique book instances

class MarkInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    car = models.ForeignKey('Car', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    mark = models.CharField(max_length=20)
    made_in = models.CharField(max_length=20)
    crooked = models.CharField(max_length=20)
    due_back = models.DateField(null=True, blank=True)


    LOAN_STATUS = (
        ('m', 'Cridit'),
        ('o', 'Satyldy'),
        ('a', 'Satylady'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text='Car Satylymda')
   

    class Meta:
        ordering = ["due_back"]



        

    def __str__(self):

        return '%s (%s)' % (self.id,self.car.car_title)


class Seller(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=30, blank=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    

    
    def get_absolute_url(self):

        return reverse('seller-detail', args=[str(self.id)])
    

    def __str__(self):

        return '{0}, {1}'.format(self.last_name,self.first_name)
   

mizamidin/views.py
from django.shortcuts import render
import datetime

from .models import Car, Seller, MarkInstance, Type

def index(request):

    num_cars=Car.objects.all().count()
    num_instances=MarkInstance.objects.all().count()
    num_instances_available=MarkInstance.objects.filter(status__exact='a').count()
    num_sellers=Seller.objects.count()  
    time=datetime.datetime.now()
    n_hour=time.hour
    n_minute=time.minute
    n_second=time.second
    n_year=time.year
    n_month=time.month
    n_day=time.day
    w_day=time.weekday
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    return render(
        request,
        'index.html',
        context={'num_cars':num_cars,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_sellers':num_sellers,'num_visits':num_visits,'hour':n_hour,'minute':n_minute,'second':n_second,'year':n_year,'month':n_month,'day':n_day,'weekday':w_day},
    )
from django.views import generic

class CarListView(generic.ListView):
    model = Car
    paginate_by = 2
class CarDetailView(generic.DetailView):
    model = Car
class SellerListView(generic.ListView):
    model = Seller
    paginate_by = 2
class SellerDetailView(generic.DetailView):
    model = Seller

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Seller

class SellerCreate(CreateView):
    model = Seller
    fields = '__all__'
    initial={'date_of_birth':'01/06/1997',}

class SellerUpdate(UpdateView):
    model = Seller
    fields = ['first_name','last_name','date_of_birth','phone']

class SellerDelete(DeleteView):
    model = Seller
    success_url = reverse_lazy('sellers')

mizamidin/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>      O ~ KOLESA.KZ ~ O      </title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row" >
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav" >
          <li><a href="{% url 'index' %}">KOLESA.KZ</a></li>
          <li><a href="{% url 'cars' %}">CARS</a></li>
          <li><a href="{% url 'sellers' %}">SELLERS</a></li>


             {% if user.is_authenticated %}
             <li>User: {{ user.get_username }}</li>
             <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
             {% else %}
             <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
             {% endif %} 
      
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
</ul>
      </div>
    </div>

  </div>
</body>
</html>

mizamidin/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1 style="background-color: gainsboro ">      O ~ KOLESA.KZ ~ O      </h1>
<div class="ss" style="background-color: LightCyan ">
  <h1><em>MiZaMiDiN</em></h1>
<p>Бүгін: {% if weekday == 6 %} Жексенбі{% endif %}{% if weekday == 5 %} Сенбі{% endif %}{% if weekday == 4 %} Жұма{% endif %}{% if weekday == 3 %} Бейсенбі{% endif %}{% if weekday == 2 %} Сарсенбі{% endif %}{% if weekday == 1 %} Сейсенбі{% endif %}{% if weekday == 0 %} Дуйсенбі{% endif %}.</p>
<p>Дата: {% if day < 10 %}0{{ day }}{% else %}{{ day }}{% endif %}/{% if month < 10 %}0{{ month }}{% else %}{{ month }}{% endif %}/{% if year < 10 %}0{{ year }}{% else %}{{ year }}{% endif %}</p>
<p>Уақыт: {% if hour < 10 %}0{{ hour }}{% else %}{{ hour }}{% endif %}:{% if minute < 10 %}0{{ minute }}{% else %}{{ minute }}{% endif %}:{% if second < 10 %}0{{ second }}{% else %}{{ second }}{% endif %}</p>
<p>Сіз бұл парақшада ( {{ num_visits }} ) рет болдыңыз.</p>

<h2>Dynamic content</h2>

  <p>The Kolesa.kz has the following record counts:</p>
  <ul>
    <li><strong>Cars:</strong> {{ num_cars }}</li>
    <li><strong>Total:</strong> {{ num_instances }}</li>
    <li><strong>Total Satylymda:</strong> {{ num_instances_available }}</li>
    <li><strong>Sellers:</strong> {{ num_sellers }}</li>
  </ul>
</div>

{% endblock %}

mizamidin/templates/mizamidin/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

mizamidin/templates/mizamidin/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

mizamidin/templates/mizamidin/car_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Car: {{ car.car_title }}</h1>

  <p><strong>Seller:</strong> <a href="{% url 'seller-detail' car.seller.pk %}">{{ car.seller }}</a></p> 
  <p><strong>Summary:</strong> {{ car.summary }}</p>
  <p><strong>ISBN:</strong> {{ car.isbn }}</p> 
  <p><strong>Language:</strong> {{ car.language }}</p>  
  <p><strong>Type:</strong> {% for type in car.type.all %} {{ type }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Informations</h4>

    {% for copy in car.markinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

mizamidin/templates/mizamidin/car_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 style="background-color: gainsboro ">CAR LIST</h1>

    {% if car_list %}
    <ul>

      {% for car in car_list %}
      <li>
        <a href="{{ car.get_absolute_url }}">{{ car.car_title }}</a> ({{car.seller}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no cars in the Kolesa.kz</p>
    {% endif %}       
{% endblock %}

mizamidin/templates/mizamidin/seller_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Seller</h1>

<p>Are you sure you want to delete the seller: {{ seller }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

mizamidin/templates/mizamidin/seller_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>SELLER: {{ seller.first_name }}, {{ seller.last_name }} </h1>
  </n>{{seller.date_of_birth}}
  <div style="margin-left:20px;margin-top:20px">
  <p><strong>CARS:</strong><a href="http://127.0.0.1:8000/mizamidin/car/1"> 1) CAR </a></p>
  <p><strong>last_name:</strong> <a href=""> {{ seller.last_name }}</a></p>
  <p><strong>first_name:</strong> <a href=""> {{ seller.first_name }}</a></p> 
  <p><strong>date_of_birth:</strong> {{ seller.date_of_birth }}</p> 
  <p><strong>phone:</strong> {{ seller.phone }}</p>  
  </div>
{% endblock %}

mizamidin/templates/mizamidin/seller_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

mizamidin/templates/mizamidin/seller_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 style="background-color: gainsboro ">SELLER LIST</h1>

    {% if seller_list %}
    <ul>

      {% for seller in seller_list %}
      <li>
        <a href="{{ seller.get_absolute_url }}">{{seller.first_name}},{{seller.last_name}}({{seller.date_of_birth}})</a> ({{seller.phone}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no sellers in the Kolesa.kz</p>
    {% endif %}       
{% endblock %}